spring.application.name=heritage-explorer

server.port=${PORT:8081}

spring.datasource.url=jdbc:mysql://fsad.cd6y0sykgtep.eu-north-1.rds.amazonaws.com/fsad
spring.datasource.username=admin
spring.datasource.password=Jalluris
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:3000,https://frontend-finally.onrender.com,https://frontend-bou1.onrender.com}
